### ISSUE TITLE
names vocab: allow names vocab to have 2 types of objects

### ISSUE THREAD

**Issue by jrcastro2** [CERNDocumentServer/cds-rdm#193]
There will be 2 types of objects in the `names` vocab: the ORCID objects, and the CERN objects.

The ORCID objects are inserted or updated via the automatic jobs/dump. Its IDs cannot really be changed as all the code relies on having the ORCID as the id:
```
- affiliations:
  - name: Northwestern University
  family_name: Findler
  given_name: Robby
  id: 0000-0002-4245-2000
  identifiers:
  - identifier: 0000-0002-4245-2000
    scheme: orcid
```

The CERN objects **could look like this** (check `props` definition in other vocabs):
```
- affiliations:
  - name: <affiliations from CERN db>
  family_name: Findler
  given_name: Robby
  id: <encrypted-person-id>
  props:
    e-mail: <email>
    username: <username>
    is_cern: True
  identifiers:
  - identifier: <encrypted-person-id>
    scheme: CERN
```

In general, the `vocabularies` schemas and features should be enhanced to support:
1. extra fields for the `names`. It looks like that it is not the case today, see [here](https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/contrib/names/jsonschemas/names/name-v1.0.0.json#L6).
2. vocabularies should support deprecation.
